name: Daily inventory scrape

on:
  schedule:
    # 7:00 AM MT is 13:00 UTC during MDT and 14:00 UTC during MST
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python src/script/toyota_scrapper.py

      - name: Commit CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain -- public/data/inventory.csv)" ]; then
            git add public/data/inventory.csv
            git commit -m "chore(data): update inventory.csv [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Trigger Vercel deploy hook (optional)
        if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != '' }}
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
